pipeline {
  agent {
    kubernetes {
      label 'podlabel'
      yaml """
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
  - name: maven
    image: gcr.io/cloud-builders/mvn
    imagePullPolicy: Always
    tty: true
    stdin: true
    command:
      - cat
  - name: jnlp
    image: 'jenkins/inbound-agent:4.3-4-alpine'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
  restartPolicy: Never
"""
    }
  }

  // tools {
  //     maven 'maven363'
  //     jdk 'jdk8'
  // }

  // stages {

  //   stage('Run maven') {
  //     steps {
  //       sh 'set'
  //       sh "echo OUTSIDE_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}"
        
  //       container('maven') {
  //         sh 'echo MAVEN_CONTAINER_ENV_VAR = ${CONTAINER_ENV_VAR}'
  //         sh 'mvn -version'
  //       }

  //     }
  //   }

  //   // stage ('Initialize') {
  //   //   steps {
  //   //     sh '''
  //   //       echo "PATH = ${PATH}"
  //   //       echo "M2_HOME = ${M2_HOME}"
  //   //     '''
  //   //   }
  //   // }

  //   // stage('Example Build') {
  //   //   steps {
  //   //     container('maven') {
  //   //       sh 'mvn clean spring-boot:build-image -Dspring-boot.build-image.imageName=gcr.io/solar-botany-297306/gs-spring-boot-start:v4'
  //   //     }
  //   //   }
  //   // }
  // }

  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
        container('busybox') {
          sh '/bin/busybox'
        }
      }
    }
  }
}
