pipeline {
  agent {
    kubernetes {
      label 'podlabel'
      yaml """
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
  - name: maven
    image: gcr.io/cloud-builders/mvn
    imagePullPolicy: Always
    tty: true
    stdin: true
    command:
      - cat
  - name: jnlp
    image: 'jenkins/inbound-agent:4.3-4-alpine'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
  - name: docker-daemon
    image: docker:19.03.1-dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  - name: docker
    image: docker:19.03.1
    command:
    - sleep
    args:
    - 99d
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  restartPolicy: Never
  volumes:
  - name: docker-socket
    emptyDir: {}
"""
    }
  }

  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'ls -al'
          sh 'mvn clean package'
        }
        container('docker') {
          sh 'ls -al'
          sh 'pwd'
          sh 'docker build . --tag=gcr.io/solar-botany-297306/gs-spring-boot-docker:v2 --no-cache'
        }        
      }
    }
  }
}
